<style>

    body {
        background: transparent;
    }

    table th {
        font-size: 14px;
        padding: 16px 10px;
        background: #e3e3e3;
        color: #212121;
        text-transform: none;
    }

    table td {
        padding: 16px 10px;
        color: #212121;
    }

    table td.action {
        padding-left: 5px;
        padding-right: 5px;
    }

    .collapsible table td {
        padding-top: 7px;
        padding-bottom: 7px;
    }

    .collapsible-body .coluna-etapa {
        padding: 0px;
        margin-bottom: 20px;
    }
    .collapsible {
        box-shadow: none;
        /*border-right: none;*/
        /*border-left: none;*/
    }
    .collapsible-header {
        padding: 8px;
    }
    .collapsible-header:hover {
        background: #fdfbfb;
    }

    .collapsible-header.produto {
        text-transform: uppercase;
    }

    .collapsible .collapsible .collapsible-header {
        padding-left: 40px;
    }

    .collapsible .collapsible-body .row {
        margin-bottom: 0px;
    }

    table .left-align {
        text-align: left !important;
    }

    table .right-align {
        text-align: right !important;
    }

    table thead tr.title {
        background: transparent;
    }

    table thead tr.title th {
        text-transform: uppercase;
        text-align: left;
        font-size: 17px;
    }

    .tabs .tab a {
        background: #fff;
        color: #212121;
    }

    .tabs .tab a:hover,
    .tabs .tab a.active {
        background-color: #c8e6c9;
        color: #212121;
    }

    .tabs .indicator {
        background-color: #4caf50;
        right: 1155.38px;
        left: 0px;
        width: 20%;
    }

    .tabs .tab {
        width:20%;
        float:left;
    }

    /*.tabs .tab:nth-child(5) {*/
        /*width:24%;*/
        /*background: red;*/
    /*}*/

    @media screen and (max-width: 768px) {
        .tabs .tab {
            width:100%;
            float:left;
        }
    }

    form .input_simples:hover,
    form .textarea_simples:hover,
    form .select_simples:hover,
    form .input_simples2:hover,
    form .input_simples,
    form .textarea_simples,
    form .select_simples,
    form .input_simples2 {
        background: none;
    }

    .input-field input[type=text]:focus {
        /*border-bottom: 1px solid #212121;*/
        /*box-shadow: 0 1px 0 0 #212121;*/
    }

    .input-field label,
    .input-field label:hover,
    .input-field:active,
    .input-field:hover,
    .input-field {
        color: #212121;

    }

    input:not([type]):focus:not([readonly]),
    input[type=text]:focus:not([readonly]),
    input[type=password]:focus:not([readonly]),
    input[type=email]:focus:not([readonly]),
    input[type=url]:focus:not([readonly]),
    input[type=time]:focus:not([readonly]),
    input[type=date]:focus:not([readonly]),
    input[type=datetime]:focus:not([readonly]),
    input[type=datetime-local]:focus:not([readonly]),
    input[type=tel]:focus:not([readonly]),
    input[type=number]:focus:not([readonly]),
    input[type=search]:focus:not([readonly]),
    textarea.materialize-textarea:focus:not([readonly]) {
        border-bottom: 1px solid #212121;
        box-shadow: 0 1px 0 0 #212121;
    }

    input:not([type]):focus:not([readonly]) + label,
    input[type=text]:focus:not([readonly]) + label,
    input[type=password]:focus:not([readonly]) + label,
    input[type=email]:focus:not([readonly]) + label,
    input[type=url]:focus:not([readonly]) + label,
    input[type=time]:focus:not([readonly]) + label,
    input[type=date]:focus:not([readonly]) + label,
    input[type=datetime]:focus:not([readonly]) + label,
    input[type=datetime-local]:focus:not([readonly]) + label,
    input[type=tel]:focus:not([readonly]) + label,
    input[type=number]:focus:not([readonly]) + label,
    input[type=search]:focus:not([readonly]) + label,
    textarea.materialize-textarea:focus:not([readonly]) + label {
        color: #212121;
    }

    input[type=text]:disabled + label,
    input[type=text]:disabled,
    input[type=text][readonly="readonly"] + label,
    input.disabled,
    input[type=text][readonly="readonly"] {
        color: rgba(33, 33, 33, 0.54);
    }

    form select.browser-default {
        min-height: 44px;
        background-color: #fafafa;
        border: 1px solid #9e9e9e;;
        width: 100%;

    }

    form textarea.materialize-textarea {
        margin-top: 10px;
        padding: 13px 10px;
        border: 1px solid #9e9e9e;
    }

    .input-field label,
    form label {
        color: #212121;
    }

    .modal.bottom-sheet {
        max-height: 50%;
    }

    .section {
        position: relative;
    }

    .btn-close-modal {
        margin-right: 10px;
    }
    .section  span.badge {
        font-size: 1.2rem;
    }

    span.badge div {
        display: inline;
        margin-left: 30px;
    }

    .section  span.badge  i {
        /*font-size: 1rem;*/
        position: absolute;
        top: 28px;
        margin-right: 30px;
    }

    .modal.modal-pre-loader {
        width: 300px;
        height: 180px;
        padding: 10px;
    }

    .modal.modal-pre-loader .modal-content {
        padding: 10px;
    }

    .table.bordered > thead > tr.outrasfontes, table.bordered > tbody > tr.outrasfontes {
        background: rgba(205, 200, 230, 0.45);
    }

    .danger.input-field {
        color: #ef6c00;
    }

    .danger.input-field input {
        border-bottom: 1px solid #ef6c00;
    }

    .danger.input-field input[type=text]:focus:not([readonly]) {
        border-bottom: 1px solid #ef6c00;
        box-shadow: 0 1px 0 0 #ef6c00;
    }

    .danger.input-field label,
    .danger.input-field label,
    .danger.input-field label:hover,
    .danger.input-field:active,
    .danger.input-field:hover,
    .danger.input-field {
        color: #ef6c00 !important;
    }

    #toast-container .toast {
        cursor: pointer;
        position: relative;
        padding-right: 40px;
    }
    #toast-container .toast::after {
        font-family: 'Material Icons';
        content: "close";
        -webkit-font-feature-settings: 'liga';
        color: #dd2c00;
        font-size: 1.5rem;
        font-weight: bold;
        float: right;
        padding-left: 10px;
        width: 100px;
        position: absolute;
        right: -55px;

    }

    #custosvinculados .preloader-wrapper {
        display: none;
    }


</style>

<div class="container-fluid">

    <div class="row">

        <?php echo $this->partial("inc/menu.phtml", $this); ?>

        <div class="content col s10 m12 l10 planilha-produtos">
            <?php
            gerarBreadCrumb(array(
                array('Lista de Propostas' => array('controller' => 'manterpropostaincentivofiscal', 'action' => 'listarproposta')),
                array('Or&ccedil;amento' => '')
            ));
            ?>

            <div class="clearfix"></div>
            <h5 class="light">Custo por produto</h5>
            <?php if( false ) : ?>
            <?php //if( $this->PlanilhaSalvo) : ?>
                <p class="right-align" style="position: absolute; top: 167px; right: 100px">
                    <a id="btn-restaurar-planilha" class="btn-floating waves-effect waves-light btn tooltipped btn-info" data-tooltip="Restaurar planilha"><i class="material-icons left">restore</i></a>
                </p>
            <?php endif; ?>
            <div id="container-list" data-ajax-render='/proposta/manterorcamento/listar-produtos/idPreProjeto/<?php echo( isset($this->idPreProjeto) ) ? $this->idPreProjeto : ''; ?>'></div>
            <div id="custosvinculados" data-ajax-render='/proposta/manterorcamento/resumo-planilha/idPreProjeto/<?php echo( isset($this->idPreProjeto) ) ? $this->idPreProjeto : ''; ?>'></div>
        </div>
    </div>
</div>
    <div id="msg"></div>
    <div id="rodapeConteudo"><span></span></div>
    <br clear="all" />
<div id="modal-pre-loader" class="modal modal-pre-loader">
    <div class="modal-header center valign"><h5>Aguarde!</h5></div>
    <div class="modal-content">
        <div class="row">
            <div class="col s4">
                <div class="preloader-wrapper small active">
                    <div class="spinner-layer spinner-blue-only">
                        <div class="circle-clipper left">
                            <div class="circle"></div>
                        </div><div class="gap-patch">
                            <div class="circle"></div>
                        </div><div class="circle-clipper right">
                            <div class="circle"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col s8">
                <p>Carregando...</p>
            </div>
        </div>
    </div>
</div>

<script>

$(document).ready(function(){
    <?php if (!$this->isEditavel) : ?>
        JSBloquearAlteracaoFormulario();
    <?php endif; ?>
});

$3(document).ajaxStart(function() {
    $3('#modal-pre-loader').modal('open');
});

$3(document).ajaxComplete(function () {
    $3('#modal-pre-loader').modal('close');
});

$3(document).ready(function ($) {

    $('.modal-pre-loader').modal();

    $('body').on('click', '.btn-salvar', function () {

        var validar = true;
        $('.valida').each(function () {
            if ($(this).val() == '') {
                validar = false;
            }
        });

        if (validar == false) {
            Materialize.toast("Dados obrigat&oacute;rios n&atilde;o informados!", 4000);
            return false;
        } else {
            if ($("#qtd").val() == 0) {
                Materialize.toast('Quantidade n&atilde;o pode ser igual a zero', 4000);
                $("#qtd").focusin();
                return false;
            }

            if ($("#ocorrencia").val() == 0) {
                Materialize.toast('Ocorr&ecirc;ncia n&atilde;o pode ser igual a zero', 4000);
                $("#ocorrencia").focusin();
                return false;
            }

            var vlunitario = $("#vlunitario").val();
            vlunitario = vlunitario.replace(/\D/g, "");
            vlunitario = vlunitario.replace(/(\d{0})(\d)/, "$1$2");

            if (vlunitario == 0) {
                Materialize.toast('Valor unit&aacute;rio n&atilde;o pode ser igual a zero', 4000);
                $("#vlunitario").focusin();
                return false;
            }

            if ($("#qtdDias").val() == 0) {
                Materialize.toast('Quantidade de dias n&atilde;o pode ser igual a zero', 4000);
                $("#qtdDias").focusin();
                return false;
            }

            if ($("#justificativa.valida").val() == '') {
                Materialize.toast('Justificativa neste caso &eacute; obrigat&oacute;ria!', 4000);
                $("#justificativa").focus();
                return false;
            }

            $.post(
                $('#form').attr('action'), $('#form').serialize(), function (response) {
                event.preventDefault();
                $.each(response, function (index, item) {
                    let uf = item.dados.UfDespesa;
                    let mun = item.dados.MunicipioDespesa;
                    let stringLocalizacao = $("select option[value='" + uf + ":" + mun + "']").text();

                    let itemHtml = ''
                        + '<tr id="item-planilha-' + item.dados.idPlanilhaProposta + '" class="green lighten-3">'
                        + '<td class="left-align aaaa">' + item.dados.itemNome + '</td>'
                        + '<td>' + item.dados.unidade + '</td>'
                        + '<td>' + item.dados.quantidade + '</td>'
                        + '<td>' + item.dados.ocorrencia + '</td>'
                        + '<td class="right-align">' + item.dados.valorUnitario + '</td>'
                        + '<td class="right-align">' + item.dados.total + '</td>'
                        + '<td class="action right-align">'
                        + '<a data-ajax-modal="' + item.dados.urlEditarProduto + '" href="javascript:void(0);" class="btn small waves-effect waves-light tooltipped btn-primary" data-position="top" data-delay="50" data-tooltip="Editar" data-ajax-modal-type="bottom-sheet">'
                        + '<i class="material-icons">edit</i>'
                        + '</a>'
                        + '</td>'
                        + '<td class="action left-align">'
                        + '<a class="btn small waves-effect waves-light tooltipped btn-danger btn-excluir-item" href="javascript:void(0);" data-tooltip="Excluir" data-ajax="' + item.dados.idPlanilhaProposta + '" ><i class="material-icons">delete</i></a>'
                        + '</td>'
                        + '</tr>';

                    if (item.status == '1') {
                        if (item.action == 'update') {

                            $("#item-planilha-" + item.idPlanilhaProposta).replaceWith(itemHtml);
                        }
                        else if (item.action == 'insert') {

                            var produto = item.dados.idProduto;
                            var etapa   = item.dados.idEtapa;
                            var idEtapa = "#etapa" + produto + "" + etapa + "" + mun;

                            $(idEtapa + " div.info").hide();
                            $(idEtapa + ' table tbody').append(itemHtml).focus();
                        }

                        if (item.close == '1')
                            $('#modal').modal('close');

                        $('#form')[0].reset();
                        Materialize.toast(stringLocalizacao + ' ' + item.msg, 4000, 'green white-text');
                    } else {
                        Materialize.toast(stringLocalizacao + ' ' + item.msg, 8000, 'red darken-1 white-text');
                    }
                });

                $.each($('#custosvinculados[data-ajax-render]'), function () {
                    $.ajaxRender({
                        strUrl: $('#custosvinculados').attr('data-ajax-render'),
                        strTarget: '#custosvinculados'
                    });
                });
            });
        }
        return false;
    });
    window.dispatchEvent(new Event('resize'));

    <?php if(false) : ?>
    <?php //if( $this->PlanilhaSalvo) : ?>
        $3('body').on('click', '#btn-restaurar-planilha', function () {

            $3("#msg").html('Tem certeza que deseja restaurar a planilha?\n Esta acao nao podera ser desfeita!');

            $("#msg").dialog
            ({
                width: 350,
                height: 200,
                modal: true,
                draggable: false,
                resizable: false,
                closeOnEscape: false,
                buttons: {
                    'N\xE3o': function () {
                        $(this).dialog('close');
                        $(this).dialog('close');
                    },
                    'Sim': function () {
                        var urlAction = "<?php echo $this->url(array('module' => 'proposta', 'controller' => 'manterorcamento', 'action' => 'restaurarplanilha')); ?>";
                        var dados = { idPreProjeto: <?php echo isset($this->idPreProjeto) ? $this->idPreProjeto : '' ?>};

                        $.post(urlAction, dados, function (result) {
                            if (result.status == '1') {
                                Materialize.toast(result.msg, 4000, 'green white-text');

                                var divRender = $('div[data-ajax-render]');

                                $3.each($3('div[data-ajax-render]'), function () {
                                    $3.ajaxRender({strUrl: $(this).attr('data-ajax-render'), strTarget: '#' + $(this).attr('id')});
                                });

                            } else {
                                Materialize.toast(result.msg, 8000, 'red darken-1 white-text');
                            }
                        });

                        $(this).dialog('close');
                    }
                }
            });

            $3(".ui-dialog-titlebar-close").remove();

            return false;

        });
    <?php endif; ?>

    $3('body').on('keyup', '#editor1', function () {
        if ($3("#editor1.valida").val() != '') {
            $3("#btn-salvar").addClass('btn-salvar').removeClass('disabled');
            $3('.mensagem1').fadeOut(function(){
                $(this).remove();
            });
        }else{
            $3("#btn-salvar").removeClass('btn-salvar').addClass('disabled');
        }
    });

    $3(document).on('click', '#toast-container .toast', function() {
        $3(this).fadeOut(function(){
            $(this).remove();
        });

    });
});
</script>